version: '3.3'
services:
  postgres:
    container_name: threads-db
    image: postgres:latest
    ports:
      - target: 5432
        published: 5432
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgresfirstdb
      POSTGRES_PASSWORD: threads

  redis:
    container_name: my-redis
    image: redis:latest
    ports:
      - target: 6379
        published: 6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
